# Trying to downlaod csv from lever directly

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

import time

driver = webdriver.Chrome()
driver.get("https://hire.lever.co/reports/export/jobPostings")

EMAIL_ID = "becandid@directi.com"
PSS = "Talent@123"


driver.find_element_by_class_name('provider-button-label').click()

elem = driver.find_element_by_id("identifierId")
elem.clear()
elem.send_keys(EMAIL_ID)
elem.send_keys(Keys.RETURN)

assert "No results, it crashed" not in driver.page_source

time.sleep(6)


elem2 = driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[1]/div[1]/div/div/div/div/div[1]/div/div[1]/input")
elem2.clear()
elem2.send_keys(PSS)
elem2.send_keys(Keys.RETURN)

time.sleep(10)

'''
Logged in 
'''

# Click to Generate small report
time.sleep(5)
elem3 = driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[2]/a").click()
time.sleep(5)

# Click to generate big report
driver.get("https://hire.lever.co/reports/export/candidates")
time.sleep(5)
elem3 = driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/a").click()
print("Gnerating all reports")
time.sleep(14*60)

print("All reports must be generated by now")

# Clicking to download
time.sleep(40)


def tryBlock(n, arrayNumber):
	xpathString = "/html/body/div["+ str(n) +"]/div/div[" + str(arrayNumber) +"]/div[2]/a"
	elem4 = driver.find_element_by_xpath(xpathString).click()
	print("download button clicked, is it downloading master?")

def closeDownloadDialog(n,arrayNumber):
	xpathString = "/html/body/div["+ str(n) +"]/div/div[" + str(arrayNumber) +"]/a"
	elem4 = driver.find_element_by_xpath(xpathString).click()
	print("download button clicked, is it downloading master?")


found = False
a=1
b=2
while found is False:
	try:
		tryBlock(a,b)
		tryBlock(a,b+1)
		print(f"({a},{b}) passed")
		print("Successful")
		found = True

		# Closing the buttons
		print("Closing the buttons")
		closeDownloadDialog(n,arrayNumber)
		closeDownloadDialog(n,arrayNumber+1)
		print("Buttons closed")
		break
	except:
		print(f"({a},{b}) failed")
		a += 1
		if a >= 18:
			print("All try except failed. They are too dynamic")
			found = False
			break



# try:
# 	tryBlock(2,2)
# 	tryBlock(2,3)
# except:
# 	try:
# 		tryBlock(11,2)
# 		tryBlock(11,3)
# 	except:
# 		try:
# 			tryBlock(12,2)
# 			tryBlock(12,3)
# 		except:
# 			print("All try except again failed. Loop now")



time.sleep(12*60)
driver.close()
	
